# Generated by Django 5.2.2 on 2025-06-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_first', models.TimeField()),
                ('interval_second', models.TimeField()),
                ('key_word', models.TextField()),
                ('ban_word', models.TextField()),
                ('promt', models.TextField()),
            ],
        ),
    ]
