# Generated by Django 5.2.2 on 2025-06-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bot_interval_first_alter_bot_interval_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='agent_promt',
            field=models.TextField(default='Я хороший менеджер'),
            preserve_default=False,
        ),
    ]
