# Generated by Django 5.2.2 on 2025-06-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bot_agent_promt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='proxy_host',
            field=models.CharField(default='host'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='proxy_password',
            field=models.CharField(default='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='proxy_port',
            field=models.CharField(default='20292'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='proxy_user',
            field=models.CharField(default='user'),
            preserve_default=False,
        ),
    ]
